### ISSUE TITLE
KernelTraceControl.dll not copied by default

### ISSUE THREAD

**Issue by kkokosa** [lowleveldesign/wtrace#7]
When building solution (both Release or Debug) required folders `amd64` and `x86` from `binaries` subdirectory are not copied to the output path. This results in the following exception during execution:
```
> wtrace.exe notepad

Unhandled Exception: System.ComponentModel.Win32Exception: The specified module could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceControl()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSession(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRACING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvider(Keywords flags, Keywords stackCapture)
   at LowLevelDesign.WinTrace.TraceCollector.Start() in F:\GithubProjects\wtrace\wtrace\TraceCollector.cs:line 38
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
Using VS 2017 Enterprsie 15.3.

**Comment by lowleveldesign** [comment]
Thanks for spotting this - I also discovered that it stopped working on Win7. Next bug coming :)
