### ISSUE TITLE
2.0 stopped working on Win7

### ISSUE THREAD

**Issue by lowleveldesign** [lowleveldesign/wtrace#8]
After replacing the Chromium PInvoke methods with PInvoke nuget packages, wtrace stopped working on Win7. To fix.

**Comment by lowleveldesign** [comment]
```
Unhandled Exception: System.ComponentModel.Win32Exception: The specified procedu
re could not be found
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.LoadKernelTraceC
ontrol()
   at Microsoft.Diagnostics.Tracing.Extensions.ETWKernelControl.StartKernelSessi
on(UInt64& TraceHandle, Void* propertyBuff, Int32 propertyBuffLength, STACK_TRAC
ING_EVENT_ID* stackTracingEventIds, Int32 cStackTracingEventIds)
   at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableKernelProvid
er(Keywords flags, Keywords stackCapture)
   at LowLevelDesign.WinTrace.TraceCollector.Start()
   at LowLevelDesign.WinTrace.TraceProcess.<>c__DisplayClass8_1.<TraceNewProcess
>b__2(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWor
kItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
